### ISSUE TITLE
Error on uninstall

### ISSUE THREAD

**Issue by koddr** [MichelleCox/filefield_paths#9]
Hello.

I see error message after click `Delete` for your module on confirm page: `./admin/modules/uninstall/confirm`.

Error:

``` html
The website encountered an unexpected error. Please try again later.
Recoverable fatal error: Argument 1 passed to Drupal\Core\Entity\EntityManager::onFieldStorageDefinitionDelete() must implement interface Drupal\Core\Field\FieldStorageDefinitionInterface, null given, called in /home/m/mysite.com/public_html/modules/filefield_paths/filefield_paths.install on line 24 and defined in Drupal\Core\Entity\EntityManager->onFieldStorageDefinitionDelete() (line 431 of core/lib/Drupal/Core/Entity/EntityManager.php).
```

And now, error message  `Notice: Undefined index: origname in filefield_paths_uninstall() (line 23 of modules/filefield_paths/filefield_paths.install).` follow all admin pages.

**Comment by koddr** [comment]
This error also show on release version Drupal 8.0.0.
And broke my site TOTALLY!

**FIX IT PLEASE!!!**

**Comment by MichelleCox** [comment]
This is an unofficial port that is not even at an alpha stage that was written against a beta release of Drupal. There is obviously some work to be done to get it working properly with the stable release of Drupal and it will be done at some point but yelling isn't going make it happen. If you don't have the skills to dig in and fix things, I suggest sticking to stable releases of modules. That's not being snarky; it's serious advice. Early dev versions are prone to bugs and site-breaking changes and are not recommended for use unless you are prepared to deal with that.

**Comment by koddr** [comment]
OK. Write in red on README.md this thing: `This version is unstable. May broken your Drupal dist. Be careful if use this`.
